### ISSUE TITLE
Add option to enter custom aprs server and port.

### ISSUE THREAD

**Issue by la9vka** [ampledata/node-red-contrib-aprs#10]
Please add config option to enter custom aprs server and port. This would enable server defined downstream filters and offline/field use.

**Comment by ampledata** [comment]
@la9vka To Clarify, do you want to send (TX) to a custom server, or receive (RX) from a custom server?

**Comment by ampledata** [comment]
@la9vka Currently you can set your TX server by passing in `msg.payload.server` set to your server hostname or IP. It doesn't seem like support for setting a port other than the default of `14580` is there, so I could add that.

**Comment by ampledata** [comment]
@la9vka added in v2.2.0: https://github.com/ampledata/node-red-contrib-aprs/blob/master/CHANGELOG.md#node-red-contrib-aprs-220
