### ISSUE TITLE
Problems sending APRS

### ISSUE THREAD

**Issue by la9vka** [ampledata/node-red-contrib-aprs#12]
I'm trying to replace my APRX installation for sending weather and telemetry data. But I get the following error:

`RangeError: Port should be >= 0 and < 65536. Received .`

If i don't enter anything in the optional fields, or if i fill inn the fields. 

If i enter a valid port number in the server field It goes to transmitting and timeout instead of the above error.

Node-red 3.0.2, node-red-contrib-aprs 2.2.0

**Comment by ampledata** [comment]
Hey @la9vka , thanks for the bug report. Can you share your flow? (hamburger menu, export)

**Comment by la9vka** [comment]
`[
    {
        "id": "5cfb3fd8d2df680a",
        "type": "tab",
        "label": "APRS Test",
        "disabled": false,
        "info": "",
        "env": []
    },
    {
        "id": "facc645f675b4edb",
        "type": "inject",
        "z": "5cfb3fd8d2df680a",
        "name": "",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "",
        "payloadType": "date",
        "x": 220,
        "y": 160,
        "wires": [
            [
                "4dcaf58855cf6f5c"
            ]
        ]
    },
    {
        "id": "4dcaf58855cf6f5c",
        "type": "function",
        "z": "5cfb3fd8d2df680a",
        "name": "Create WorldMap JSON",
        "func": "// APRS TX Node uses WorldMap serialized data:\nmsg.payload = {\n    from: { call: \"LA9VKA\", ssid: \"13\" },\n    data: {\n        latitude: 59.0000,\n            longitude: 11.000,\n//                extension: { courseDeg: 239, speedMPerS: 1.543333332 },\n        weather: {\n//            windGust: 4.4704,\n                temperature: 71.000,\n                    rain1h: 0,\n                        rain24h: 0,\n//                            rainSinceMidnight: 2.794,\n                                pressure: 1000.0,\n                                    humidity: 83,\n//                                        luminosity: 0\n        },\n        comment: \"Test WX\",\n            timestamp: \"2023-01-23T18:21:00.000Z\"\n    }\n}\nreturn msg;",
        "outputs": 1,
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "libs": [],
        "x": 410,
        "y": 160,
        "wires": [
            [
                "7a2f162d68cd375b"
            ]
        ]
    },
    {
        "id": "a1f2a2e37a29e6fe",
        "type": "comment",
        "z": "5cfb3fd8d2df680a",
        "name": "APRS TX Example",
        "info": "This example creates a test WorldMap payload, serializses it as an APRS packet, and sends it to the APRS-IS backbone.",
        "x": 230,
        "y": 120,
        "wires": []
    },
    {
        "id": "9e2a18025c353277",
        "type": "debug",
        "z": "5cfb3fd8d2df680a",
        "name": "debug 8",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "false",
        "statusVal": "",
        "statusType": "auto",
        "x": 740,
        "y": 360,
        "wires": []
    },
    {
        "id": "61fec9af7be0237b",
        "type": "aprs rx",
        "z": "5cfb3fd8d2df680a",
        "name": "",
        "user": "LA9VKA-13",
        "url": "ws://srvr.aprs-is.net:8080",
        "filter": "r/59/11/100",
        "x": 500,
        "y": 360,
        "wires": [
            [
                "9e2a18025c353277"
            ]
        ]
    },
    {
        "id": "7a2f162d68cd375b",
        "type": "aprs tx",
        "z": "5cfb3fd8d2df680a",
        "name": "",
        "aprsConfig": "d972664a9d960733",
        "from": "",
        "to": "",
        "via": "",
        "server": "",
        "port": "",
        "x": 670,
        "y": 160,
        "wires": []
    },
    {
        "id": "d972664a9d960733",
        "type": "aprs config",
        "filter": "",
        "name": "",
        "pass": "19892"
    }
]`

**Comment by ampledata** [comment]
Fixed in 3.0.0 release

**Comment by la9vka** [comment]
Thank you! It requires a port number in properties, and package does not make it to tier2 if I enter a server into server field, but as long as port is set to 14580 and server field is empty it works :)
