### ISSUE TITLE
two different errors send APRS

### ISSUE THREAD

**Issue by w5nmr** [ampledata/node-red-contrib-aprs#14]
hey,

since the update to 2.2.0

before that everything was working fine

get two different error messages:

In the example String Payload : Error:Error: Missing longitude value 

In the example Object Payload : RangeError: Port should be >= 0 and < 65536. Received 

the same as la9vka described

node-red 3.0.2, node-red-contrib-aprs 2.2.0

translated by Google

vy 73 Peter DL1EEM/W5NMR

**Comment by ampledata** [comment]
Fixed in 3.0.0 release
