### ISSUE TITLE
"General: Error: Header - body delimiter not found"

### ISSUE THREAD

**Issue by vorpalhex** [ampledata/node-red-contrib-aprs#6]
APRS is getting connected for me but returning the following error: `"General: Error: Header - body delimiter not found"`

Here's the full response object:
```
{"payload":{"raw":"# javAPRSSrvr 4.3.2b85","errors":["General: Error: Header - body delimiter not found"]},"_msgid":"a8086cb2d1c6f82b"}
```

Any advice? Thanks.

**Comment by ampledata** [comment]
Mind posting the flow you're using, or at least a screenshot?

--
Greg Albrecht ***@***.***> W2GMD
EMT. Disaster & Emergency Information Communications Technology (ICT)
Specialist.
Mobile: 1-415-598-8226
https://ampledata.org/

**Comment by vorpalhex** [comment]
Ok, it looks like this was tied to my filter. I was using the value `o/IAN`. Using the default filter provided seems to work.
