### ISSUE TITLE
TypeError: Aprs is not a constructor

### ISSUE THREAD

**Issue by secstwice** [ampledata/node-red-contrib-aprs#9]
Hi. I get an error as in TypeError: Aprs is not a constructor using the APRS RX node. No matter what I enter I get the same error. The TX node works. I know this isnt much of a description but point me in the right direction to help debug and lets see what we come up with

**Comment by la9vka** [comment]
I get the same error. aprs 2.1.1 and node-red 3.02

**Comment by f4iyy** [comment]
Hi @ampledata & @janakj

Same here: NodeRED 3.02, running on Docker. 

docker logs -f nodered
21 Feb 12:59:39 - [info] Stopping flows
...
21 Feb 12:59:39 - [info] Stopped flows
21 Feb 12:59:39 - [info] Updated flows
21 Feb 12:59:39 - [info] Starting flows
...
21 Feb 12:59:39 - [error] [aprs rx:7b7f260815b4199a] TypeError: Aprs is not a constructor
21 Feb 12:59:39 - [info] Started flows
...

And of course APRS RX node remains disconnected.

I have rollback to v2.2.3 but same symptoms.

Thank you for your update.

L.

**Comment by ampledata** [comment]
@secstwice @la9vka @f4iyy I appreciate your patience, this was a dumb error on my part and has been fixed in v2.1.3

**Comment by f4iyy** [comment]
Thank you so much @ampledata

**Comment by secstwice** [comment]
Thank you
